[workspace]
resolver = "2"
members = ["minidb", "minidb-shared", "minidb-utils"]

[workspace.package]
authors = ["DarkCeptor44"]
edition = "2021"
license = "lgpl-3.0-or-later"
homepage = "https://github.com/DarkCeptor44/minidb"
repository = "https://github.com/DarkCeptor44/minidb"

[workspace.dependencies]
anyhow = "^1"
