[workspace]
resolver = "2"
members = ["crates/minidb", "crates/minidb-shared", "crates/minidb-utils"]

[workspace.package]
authors = ["DarkCeptor44"]
edition = "2021"
license = "lgpl-3.0-or-later"
repository = "https://github.com/DarkCeptor44/minidb.git"
