[package]
name = "minidb-shared"
description = "Shared types for minidb"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
rust-version = "1.78"
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
thiserror = "^2"
