[package]
name = "minidb"
description = "Minimalistic file-based database written in Rust"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
parking_lot = "^0.12"
