[package]
name = "minidb"
version = "0.1.0"
description = "Minimalistic file-based database written in Rust"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
cuid2 = "^0.1"
minidb-macros = { path = "../minidb-macros" }
minidb-utils = { path = "../minidb-utils" }
parking_lot = "^0.12"
rayon = "^1"
serde = { version = "^1", features = ["derive"] }
tempfile = "^3"
thiserror.workspace = true

[dev-dependencies]
divan = "^0.1"
paste = "^1"
rand = "^0.9"
